-- AlterTable
ALTER TABLE `GroupsRolesPermissions` MODIFY `permission` ENUM('VMS', 'EXERCISES', 'MANAGE_VMS', 'MANAGE_EXERCISES', 'MANAGE_MEMBERS', 'MANAGE_CODES', 'MANAGE_ROLES', 'MANAGE_SETTINGS', 'ADMINISTRATOR') NOT NULL;
