-- CreateTable
CREATE TABLE `PVENodes` (
    `UUID` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `maxVMs` INTEGER NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`UUID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
